In [1]:
import pandas as pd

data = {
    "product": ["Soap", "Shampoo", "Face Wash", "Soap", "Lotion"],
    "price": [50, 150, 120, 50, None],
    "quantity": [2, 1, 3, 2, 4]
}

df = pd.DataFrame(data)

df.to_csv("sales.csv", index=False)

print("sales.csv created")

sales.csv created

In [2]:
import pandas as pd

df = pd.read_csv("sales.csv")
df

     product  price  quantity
0       Soap   50.0         2
1    Shampoo  150.0         1
2  Face Wash  120.0         3
3       Soap   50.0         2
4     Lotion    NaN         4

In [3]:
print("Head:")
print(df.head())

print("\nTail:")
print(df.tail())

print("\nShape:")
print(df.shape)

print("\nColumns:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

Head:
     product  price  quantity
0       Soap   50.0         2
1    Shampoo  150.0         1
2  Face Wash  120.0         3
3       Soap   50.0         2
4     Lotion    NaN         4

Tail:
     product  price  quantity
0       Soap   50.0         2
1    Shampoo  150.0         1
2  Face Wash  120.0         3
3       Soap   50.0         2
4     Lotion    NaN         4

Shape:
(5, 3)

Columns:
Index(['product', 'price', 'quantity'], dtype='object')

Data Types:
product      object
price       float64
quantity      int64
dtype: object

In [4]:
print(df.isnull().sum())

product     0
price       1
quantity    0
dtype: int64

In [5]:
df["price"] = df["price"].fillna(df["price"].mean())

df

     product  price  quantity
0       Soap   50.0         2
1    Shampoo  150.0         1
2  Face Wash  120.0         3
3       Soap   50.0         2
4     Lotion   92.5         4

In [6]:
df[["product", "price"]]

     product  price
0       Soap   50.0
1    Shampoo  150.0
2  Face Wash  120.0
3       Soap   50.0
4     Lotion   92.5

In [7]:
filtered_df = df[df["price"] > 100]

filtered_df

     product  price  quantity
1    Shampoo  150.0         1
2  Face Wash  120.0         3

In [8]:
df = df.drop_duplicates()

df

     product  price  quantity
0       Soap   50.0         2
1    Shampoo  150.0         1
2  Face Wash  120.0         3
4     Lotion   92.5         4

In [9]:
df["total_amount"] = df["price"] * df["quantity"]

df

/tmp/ipykernel_1917/1193221229.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["total_amount"] = df["price"] * df["quantity"]

     product  price  quantity  total_amount
0       Soap   50.0         2         100.0
1    Shampoo  150.0         1         150.0
2  Face Wash  120.0         3         360.0
4     Lotion   92.5         4         370.0

In [10]:
df.to_csv("cleaned_sales.csv", index=False)

print("cleaned_sales.csv saved")

cleaned_sales.csv saved

In [11]:
from google.colab import files

files.download("sales.csv")
files.download("cleaned_sales.csv")

# Summary

- Loaded sales.csv into a Pandas DataFrame.
- Explored the dataset using head(), tail(), shape, columns, and dtypes.
- Identified missing values and filled them using the mean price.
- Performed filtering and column selection operations.
- Removed duplicate records.
- Created a new column: total_amount = price * quantity.
- Saved the cleaned dataset as cleaned_sales.csv.